# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='force_migration',
            field=models.TextField(default='wtf'),
        ),
    ]
