# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='InTouch', max_length=20),
        ),
    ]
