# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_auto_20160216_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('software_category', models.CharField(choices=[('intouch', 'InTouch'), ('sys-plat', 'System Platform'), ('workflow', 'Workflow')], default='intouch', max_length=20)),
                ('force_migration', models.TextField(default='wtf')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='article2',
            name='author',
        ),
        migrations.DeleteModel(
            name='Article2',
        ),
    ]
