# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20160216_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='force_migration',
        ),
    ]
