# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_force_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='software_category',
            new_name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
