# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20160216_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('InTouch', 'InTouch'), ('System Platform', 'System Platform'), ('Workflow', 'Workflow')], default='InTouch', max_length=20),
        ),
    ]
